import type {Dispatch,SetStateAction,RefObject} from 'react'
import {ArrowDownToLine,ArrowRight,ArrowUpRight,AudioLines,Beaker,Bug,Check,ChevronDown,Code2,Copy,Dna,ExternalLink,FlaskConical,GitBranch,Leaf,Loader2,Pause,Play,Plus,RotateCcw,Settings2,ShieldCheck,Sparkles,Swords,Terminal,Trophy,UserRound,X} from 'lucide-react'
import {api} from '../../api'
import {ArenaCanvas} from '../../ArenaCanvas'
import type {ArenaMap,AuthSettings,Fly,Frame,Identity,Match,Preview,Report,Scene,Season,Spec} from '../../types'
import {colors,modes,num} from '../../types'
import {useI18n} from '../../shared/i18n'
type Set<T>=Dispatch<SetStateAction<T>>

type Props={login:boolean;setLogin:Set<boolean>;authSettings:AuthSettings|null;error:string;setError:Set<string>;loginNyxID:()=>void;identityName:string;setIdentityName:Set<string>;season:Season|null;invite:string;setInvite:Set<string>;busy:string;register:()=>Promise<void>;setIdentity:Set<Identity|null>;showToken:boolean;setShowToken:Set<boolean>;identity:Identity|null;freshToken:string;setFreshToken:Set<string>;setToast:Set<string>;createAgentToken:()=>Promise<void>;agentTokens:{id:string;expires:number}[];setAgentTokens:Set<{id:string;expires:number}[]>;action:(label:string,fn:()=>Promise<void>)=>Promise<void>;logout:()=>Promise<void>}
export function AuthDialogs({login,setLogin,authSettings,error,setError,loginNyxID,identityName,setIdentityName,season,invite,setInvite,busy,register,setIdentity,showToken,setShowToken,identity,freshToken,setFreshToken,setToast,createAgentToken,agentTokens,setAgentTokens,action,logout}:Props){const {t}=useI18n();return <>    {login&&<div className="modal-backdrop"><section className="modal"><button className="modal-close icon-button" onClick={()=>setLogin(false)} aria-label={t("关闭")}><X size={19}/></button><span className="modal-icon"><Leaf size={26}/></span><div className="eyebrow">{t("WELCOME TO THE PLAYGROUND")}</div><h2>{t("为你的设计署名。")}</h2><p>{authSettings?.mode==='nyxid'?t("使用已有 NyxID 身份，无需再注册 Arena 账号。"):t("创建一个设计师身份，保存果蝇、运行比赛，并让你的 AI 使用同一身份参与。")}</p>{error&&<p role="alert" className="error-banner">{error}</p>}{authSettings?.mode==='nyxid'?<><button className="primary wide" onClick={loginNyxID}>{t("通过 NyxID 登录")}<ArrowRight size={16}/></button><small>{t("首次确认身份权限，之后在会话有效期内直接进入。当前设计会保留。")}</small></>:!authSettings?<p>{t("正在加载登录方式…")}</p>:<><label className="field-label">{t("设计师名称")}</label><input autoFocus value={identityName} onChange={e=>setIdentityName(e.target.value)} placeholder={t("例如：Lexa / My Research Agent")} maxLength={48}/>{season?.invite_required&&<><label className="field-label">{t("内测邀请码")}</label><input value={invite} onChange={e=>setInvite(e.target.value)} placeholder={t("输入邀请码")}/></>}<button className="primary wide" disabled={!!busy} onClick={register}>{busy==='identity'?<Loader2 className="spin" size={16}/>:<Plus size={16}/>}{t("创建身份")}</button><small>{t("当前工作区中，已发布果蝇与比赛回放公开可见。")}</small><details><summary>{t("已有 API token？")}</summary><input aria-label={t("已有 API token")} type="password" placeholder={t("粘贴你自己的 token")} onKeyDown={async e=>{if(e.key==='Enter'){const token=e.currentTarget.value;try{const user=await api<Omit<Identity,'token'>>('/me',{headers:{Authorization:`Bearer ${token}`}});const id={...user,token};setIdentity(id);localStorage.setItem('flyarena.identity',JSON.stringify(id));setLogin(false)}catch(err){setError(String(err))}}}}/><small>{t("按 Enter 连接已有身份")}</small></details></>}</section></div>}
    {showToken&&identity&&<div className="modal-backdrop"><section className="modal"><button className="modal-close icon-button" onClick={()=>setShowToken(false)} aria-label={t("关闭")}><X size={19}/></button><Terminal size={28}/><h2>{identity.name}</h2><p>{identity.token?t("你的 agent 可以用这个 Bearer token 调用 API。请保存在自己的凭据管理器中。"):t("已通过 NyxID 登录。网页无需 API token；需要 AI 代你提交时，可以单独创建一个 30 天有效的 Arena token。")}</p>{error&&<p role="alert" className="error-banner">{error}</p>}{(identity.token||freshToken)?<><input aria-label="API token" type="password" readOnly value={identity.token||freshToken}/><button className="primary wide" onClick={()=>navigator.clipboard.writeText(identity.token||freshToken).then(()=>setToast(t("API token 已复制。")))}><Copy size={15}/>{t("复制 API token")}</button>{freshToken&&<small>{t("仅显示这一次，关闭后不可再次读取。")}</small>}</>:<button className="primary wide" disabled={!!busy} onClick={createAgentToken}>{t("为 AI 创建 API token")}</button>}{!identity.token&&agentTokens.map(key=><div className="color-row" key={key.id}><span>{key.id.slice(0,8)} · {new Date(key.expires*1000).toLocaleDateString()} {t("到期")}</span><button className="text-link" disabled={!!busy} onClick={()=>action('revoke',async()=>{await api('/auth/agent-tokens/'+key.id,{method:'DELETE'});setFreshToken('');setAgentTokens(await api('/auth/agent-tokens'))})}>{t("撤销")}</button></div>)}<button className="text-link" disabled={!!busy} onClick={logout}>{t("退出当前浏览器身份")}</button></section></div>}
</>
}
