import type {Frame,ReplayEvent} from '../../types'
import {useI18n} from '../../shared/i18n'
import {eventLabels,preEventBaseline,rateChanges,responseFrame} from './brainResponse'

export function BrainEventLens({moments,event,pinned,onSelect,onFollow,baseline,changes,frame,frames,slot,onFocus}:{moments:ReplayEvent[];event:ReplayEvent|null;pinned:boolean;onSelect:(e:ReplayEvent,delay?:number)=>void;onFollow:()=>void;baseline:ReturnType<typeof preEventBaseline>;changes:ReturnType<typeof rateChanges>;frame:Frame|undefined;frames:Frame[];slot:number;onFocus:(id:string)=>void}){
 const {locale}=useI18n(),zh=locale==='zh-CN',name=(e:ReplayEvent)=>eventLabels[e.type]?.[zh?0:1]||e.type
 const index=event?moments.findIndex(e=>e.tick===event.tick&&e.type===event.type):-1,sense=frame?.senses?.[slot]
 return <section className="brain-event-lens" aria-label={zh?'行为与神经变化':'Behavior and neural changes'}>
  <div className="brain-event-heading"><strong>{zh?'行为与神经变化':'Observe behavior and neural changes'}</strong><button onClick={onFollow} aria-pressed={!pinned}>{zh?'跟随比赛事件':'Follow match events'}</button></div>
  <div className="brain-event-picker"><button disabled={index<=0} aria-label={zh?'上一个脑图事件':'Previous brain event'} onClick={()=>onSelect(moments[index-1])}>←</button><select aria-label={zh?'脑图行为事件':'Brain behavior event'} value={index} onChange={e=>{const chosen=moments[Number(e.target.value)];if(chosen)onSelect(chosen)}}><option value={-1} disabled>{zh?'尚无行为事件':'No behavior event yet'}</option>{moments.map((e,i)=><option key={i} value={i}>{(e.tick/10000).toFixed(2)} s · {name(e)}</option>)}</select><button disabled={index>=moments.length-1} aria-label={zh?'下一个脑图事件':'Next brain event'} onClick={()=>onSelect(moments[index+1])}>→</button></div>
  {event&&<div className="brain-event-stamp"><b>{name(event)} · {(event.tick/10000).toFixed(2)} s</b><span>{zh?'当前距事件':'Current offset'} {((frame?.time??0)-event.tick/10000)>=0?'+':''}{((frame?.time??0)-event.tick/10000).toFixed(2)} s{event.type==='intake'&&event.amount!==undefined?` · +${event.amount.toFixed(3)}`:''}{event.objects?.length?' · '+event.objects.join(', '):''}</span></div>}
  <div className="brain-event-now"><span>{zh?'当前食物接触':'Food contact now'}: <b>{sense?.contact_food===undefined?'—':sense.contact_food.join(', ')||(zh?'无':'none')}</b></span><span>{zh?'当前环境接触':'Environment contact now'}: <b>{sense?.contact_environment===undefined?'—':sense.contact_environment.join(', ')||(zh?'无':'none')}</b></span><span>{zh?'累计摄入':'Total intake'}: <b>{frame?.scores?.[slot]?.toFixed(3)??'—'}</b></span></div>
  {baseline?<p>{zh?'基准：事件前 100 ms 内的实际采样均值':'Baseline: mean of actual samples within 100 ms before the event'} · {baseline.start.toFixed(2)}–{baseline.end.toFixed(2)} s · {changes.length} {zh?'个配对节点':'paired neurons'}</p>:<p>{zh?'没有事件前的采样，暂不显示差值；起始时的网络活动不能当作进食响应。':'No pre-event samples: changes are unavailable. Network startup activity is not a feeding response.'}</p>}
  <div className="brain-event-jumps"><button disabled={!baseline} onClick={()=>{if(event&&baseline)onSelect(event,-1)}}>{zh?'事件前':'Before event'}</button>{([.1,.5] as const).map(delay=><button key={delay} data-delay={delay} disabled={!event||!responseFrame(frames,event,delay)} onClick={()=>{if(event)onSelect(event,delay)}}>{zh?'事件后':'After event'} {delay*1000} ms</button>)}</div>
  {!!changes.length&&<button className="brain-focus-response" onClick={()=>onFocus(changes[0].id)}>{zh?'放大主要响应神经元':'Focus strongest change'}</button>}
  {!!changes.length&&<div className="brain-event-changes">{changes.slice(0,3).map(n=><button key={n.id} onClick={()=>onFocus(n.id)}><span>{n.id}</span><b>{n.delta>=0?'+':''}{n.delta.toFixed(1)} Hz</b><small>{n.before.toFixed(1)} → {n.current.toFixed(1)}</small></button>)}</div>}
  <small>{zh?'亮度显示变化幅度，表中 ± 表示升高或降低。事件按时间对齐，不证明因果；进食记账与接触食物是不同记录。':'Brightness shows change magnitude; ± shows increases or decreases. Event timing does not establish causality. Intake accounting and food contact are distinct records.'}</small>
 </section>
}
