import {ObservationDuration} from './ObservationDuration'
import {applyExperimentPreset,experimentPresets,presetAvailable} from './experimentPresets'
import {useEffect,useRef,useState} from 'react'
import type {Dispatch,SetStateAction} from 'react'
import type {ArenaMap,Fly,Identity,Season} from '../../types'
import {compatibleSensory,playableProfile} from '../../types'
import {savedFlyLabel} from '../../shared/flyIdentity'
import {useI18n} from '../../shared/i18n'
import {WildTypeChallenge} from './WildTypeChallenge'
import {buildExperimentPlan,experimentIntent,experimentScore,intentMode,opponentGroup,opponentReason} from './experimentSetup'
import type {ExperimentIntent,ExperimentPlan} from './experimentSetup'

type Set<T>=Dispatch<SetStateAction<T>>
type Props={flies:Fly[];identity:Identity|null;season:Season|null;maps:ArenaMap[];selected:string;setSelected:Set<string>;opponent:string;setOpponent:Set<string>;mode:string;setMode:Set<string>;mapId:string;setMapId:Set<string>;seedText:string;setSeedText:Set<string>;duration:number;setDuration:Set<number>;bridgeProfile:string;setBridgeProfile:Set<string>;sensoryProfile:string;setSensoryProfile:Set<string>;busy:string;startMatch:(plan:ExperimentPlan)=>Promise<void>;onPreview:()=>void;onDesign?:()=>void;preparedPlan?:boolean;onPreparedPlanShown?:()=>void}
export function ExperimentSetup({flies,identity,season,maps,selected,setSelected,opponent,setOpponent,mode,setMode,mapId,setMapId,seedText,setSeedText,duration,setDuration,bridgeProfile,setBridgeProfile,sensoryProfile,setSensoryProfile,busy,startMatch,onPreview,onDesign,preparedPlan=false,onPreparedPlanShown}:Props){
 const {t,locale}=useI18n()
 const [detailsOpen,setDetailsOpen]=useState(preparedPlan)
 const planSummary=useRef<HTMLElement|null>(null)
 useEffect(()=>{if(preparedPlan&&!detailsOpen)setDetailsOpen(true)},[preparedPlan,detailsOpen])
 useEffect(()=>{
  if(!preparedPlan||!detailsOpen)return
  planSummary.current?.scrollIntoView?.({block:'start',behavior:'smooth'});planSummary.current?.focus?.({preventScroll:true});onPreparedPlanShown?.()
 },[preparedPlan,detailsOpen,onPreparedPlanShown])
 const intent=experimentIntent(mode),subject=flies.find(f=>f.id===selected),rival=flies.find(f=>f.id===opponent)
 const {plan,errors}=buildExperimentPlan({selected,opponent,mode,mapId,seedText,duration,bridgeProfile,sensoryProfile},flies,maps,season)
 const eligibleMaps=maps.filter(m=>intentMode(intent,m)),selectedMap=maps.find(m=>m.id===mapId),profile=season?.match_profiles?.find(p=>p.id===bridgeProfile)
 const groups=['WT reference','Official reference','Your other saved designs','Public designs']
 function changeIntent(value:ExperimentIntent){setMode(value==='contact'?'duel':value);setMapId('');onPreview()}
 return <section className="match-setup experiment-setup panel" aria-label={t('Arena experiment setup')}><div className="panel-heading"><h2>{t('Arena experiment setup')}</h2><button className="text-link" onClick={onPreview}>{t('Preview setup')}</button></div>
 <p>{t('Choose the question, participants and conditions. Review the exact plan before starting computation.')}</p>
 <fieldset disabled={!!busy}><section aria-label={t('presets.title')}><h3>{t('presets.title')}</h3><p>{t('presets.editable')}</p><div className="experiment-presets">{experimentPresets.map(preset=>{const next=applyExperimentPreset(preset,{selected,opponent,mode,mapId,seedText,duration,bridgeProfile,sensoryProfile},flies),active=mapId===next.mapId&&mode===next.mode&&seedText===next.seedText&&duration===next.duration&&opponent===next.opponent;return <article className={'experiment-preset'+(active?' selected':'')} key={preset.id} aria-labelledby={'preset-'+preset.id}><h4 id={'preset-'+preset.id}>{t('presets.'+preset.id+'.question')}</h4><p className="capability-note" id={'preset-scope-'+preset.id}>{t('presets.'+preset.id+'.scope')}{!presetAvailable(preset,maps)&&<> {t('presets.unavailable')}</>}</p><button type="button" className="secondary" aria-pressed={active} aria-describedby={'preset-'+preset.id+' preset-scope-'+preset.id} disabled={!presetAvailable(preset,maps)} onClick={()=>{setMapId(next.mapId);setMode(next.mode);setOpponent(next.opponent);setSeedText(next.seedText);setDuration(next.duration);setDetailsOpen(true);onPreview()}}>{t('presets.use')}{active&&<span> · {t('presets.selected')}</span>}</button></article>})}</div></section><button type="button" className="secondary custom-experiment" onClick={()=>setDetailsOpen(true)}>{t('presets.custom')}</button><div className="experiment-details" hidden={!detailsOpen}>
 <div className="experiment-fields">
 <div><label className="field-label" htmlFor="experiment-intent">{t('Experiment intent')}</label><select id="experiment-intent" aria-label={t('比赛模式')} value={intent} onChange={e=>changeIntent(e.target.value as ExperimentIntent)}><option value="forage">{t('Solo observation')}</option><option value="contest">{t('Finite-food competition')}</option><option value="contact">{t('Contact-territory contest')}</option></select>
 <label className="field-label" htmlFor="experiment-subject">{t('你的果蝇')}</label><select id="experiment-subject" aria-label={t('参赛果蝇')} value={selected} onChange={e=>{setSelected(e.target.value);onPreview()}}><option value="">{t('Select a saved design')}</option>{flies.map(f=><option key={f.id} value={f.id} title={`${f.name} · ${f.id}`}>{savedFlyLabel(f,identity?.id,t)}</option>)}</select>
 {intent!=='forage'?<><label className="field-label" htmlFor="experiment-opponent">{t('对手')}</label><select id="experiment-opponent" aria-label={t('对手')} value={opponent} onChange={e=>{setOpponent(e.target.value);onPreview()}}><option value="">{t('Choose an opponent')}</option>{opponent&&!rival&&<option value={opponent} disabled>{opponent} · {t('Unavailable saved design')}</option>}{groups.map(group=><optgroup key={group} label={t(group)}>{flies.filter(f=>opponentGroup(f,identity?.id)===group).map(f=>{const reason=opponentReason(subject,f,bridgeProfile);return <option key={f.id} value={f.id} disabled={!!reason} title={`${f.name} · ${f.id}${reason?' · '+t(reason):''}`}>{savedFlyLabel(f,identity?.id,t)}{reason?' · '+t(reason):''}</option>})}</optgroup>)}</select><p className="capability-note">{t('References use server-owned provenance. Comparisons require distinct flies with the same connectome and neural model; disabled choices explain why.')}</p></>:<p className="capability-note">{t('Solo observation uses only your selected fly. No opponent is submitted.')}</p>}
 <WildTypeChallenge flies={flies} selected={selected} onPrepare={preset=>{setOpponent(preset.reference.id);setMode(preset.mode);setMapId(preset.map_id);setSeedText(String(preset.seed));setDuration(preset.duration_seconds);setDetailsOpen(true);onPreview()}}/>
 </div><div><label className="field-label">{t('竞技环境')}</label><div className="map-options" role="group" aria-label={t('Maps for this intent')}>{eligibleMaps.map(m=><button key={m.id} aria-pressed={m.id===mapId} className={m.id===mapId?'selected':''} onClick={()=>{setMapId(m.id);setMode(intentMode(intent,m)!);onPreview()}}><span style={{background:m.color}}/>{locale==='en'?m.english:m.name}</button>)}</div>{!eligibleMaps.length&&<p role="status">{t('No maps are available for this intent on this deployment.')}</p>}
 <div className="two-fields"><ObservationDuration value={duration} onChange={setDuration}/><label>{t('Seeds (1–3)')}<input aria-label={t('Seeds (1–3)')} value={seedText} onChange={e=>setSeedText(e.target.value)} placeholder="42, 43, 44"/></label></div>
 <p className="capability-note">{t('Seeds are distinct nonnegative int32 values. Duration is simulated time, not wall-clock time; computation can be much slower.')}</p>
 <details className="advanced-settings"><summary>{t('Advanced settings')}</summary><div><label className="field-label" htmlFor="bridge-profile">{t('Match scientific profile')}</label><select id="bridge-profile" value={bridgeProfile} onChange={e=>setBridgeProfile(e.target.value)}><option value="" disabled>{t('Select a match profile')}</option>{bridgeProfile&&!profile&&<option value={bridgeProfile} disabled>{bridgeProfile} · {t('Profile unavailable')}</option>}{season?.match_profiles?.map(p=><option key={p.id} value={p.id} disabled={!playableProfile(p)}>{t(p.id==='legacy-v1'?'Legacy v1':p.id==='sensorimotor-research-v2'?'Experimental sensorimotor v2':p.name)} · {t(playableProfile(p)?'Profile ready':'Profile unavailable')}</option>)}</select>{season?.match_profiles?.filter(p=>!playableProfile(p)).map(p=><p key={p.id} className="capability-note">{p.id}: {p.reason||t('Profile unavailable')}</p>)}
 <label className="field-label" htmlFor="experiment-senses">{t('Sensory input profile')}</label><select id="experiment-senses" aria-label={t('Sensory input profile')} value={sensoryProfile} onChange={e=>setSensoryProfile(e.target.value)}><option value="odor-only-v1">{t('Bilateral odor only')}</option>{sensoryProfile&&sensoryProfile!=='odor-only-v1'&&!season?.sensory_profiles?.some(p=>p.id===sensoryProfile)&&<option value={sensoryProfile} disabled>{sensoryProfile} · {t('Profile unavailable')}</option>}{season?.sensory_profiles?.filter(p=>p.id!=='odor-only-v1'&&(compatibleSensory(season,bridgeProfile,p.id)||p.id===sensoryProfile)).map(p=><option key={p.id} value={p.id} disabled={!p.ready||!compatibleSensory(season,bridgeProfile,p.id)}>{t(p.name||p.id)} · {t(p.ready&&compatibleSensory(season,bridgeProfile,p.id)?'Profile ready':'Profile unavailable')}</option>)}</select>
 <p className="capability-note">{t('Experimental sandbox. Results stay outside the public leaderboard. Neural dynamics, sensory encoding and motor readout are declared engineering models, not validated natural aggression or intelligence.')}</p></div></details>
 </div></div>
 <section ref={planSummary} tabIndex={-1} className="experiment-plan" aria-label={t('Plan before submission')} aria-live="polite"><h3>{t('Plan before submission')}</h3><p><b>{subject?.name||t('Select a saved design')}</b>{intent!=='forage'&&<> vs <b>{rival?.name||t('Choose an opponent')}</b></>} · {selectedMap?(locale==='en'?selectedMap.english:selectedMap.name):t('Choose a map offered for this intent.')} · <code>{mode}</code></p>
 <p><code>{selected||'—'}{intent!=='forage'&&<> / {opponent||'—'}</>}</code></p><p><code>{bridgeProfile||'—'} · {sensoryProfile}</code> · {t(playableProfile(profile)?'Profile ready':'Profile unavailable')}</p>
 <p>{intent==='forage'?t('One solo match per seed; no position-swapped pairing.'):t('Two matches per seed: your fly in slot 1, then slot 2. Positions are swapped with identical seeds and conditions.')}</p>
 <p>{t(experimentScore(mode,mapId,selectedMap?.metadata))}</p>
 {plan&&<><p className="experiment-plan-total"><strong>{plan.matches.length}</strong> {t('matches')} · <strong>{duration}</strong> {t('simulated seconds per match')} · <strong>{plan.matches.length*duration}</strong> {t('simulated seconds total')}</p><p>{t('Seeds')}: {plan.seeds.join(', ')} · {t('Layout preview uses the first seed.')}</p><details><summary>{t('Inspect every planned match')}</summary><ol>{plan.matches.map((m,i)=><li key={i}>{t('Match')} {i+1} · {t('Seed')} {m.seed} · {t('Slot')} 1: <code>{m.fly_ids[0]}</code>{m.fly_ids[1]&&<> · {t('Slot')} 2: <code>{m.fly_ids[1]}</code></>}</li>)}</ol></details></>}
 {plan?.submissions[0]?.endpoint==='/observation-series'&&<p>{t('observation.durable')}</p>}
 {errors.length>0&&<ul className="experiment-errors" role="status">{errors.map(e=><li key={e}>{t(e)}</li>)}</ul>}
 <p className="capability-note">{t('Only verified recorded results can be compared. Failed or unfinished runs remain visible and provide no successful comparison.')}</p>
 </section><button className="primary wide" disabled={!!busy||!plan} onClick={()=>{if(plan)void startMatch(plan)}}>{t(busy?'Submitting experiment…':intent==='forage'?'Run my simulation':'创建双循环系列赛')}</button>
 </div>
 </fieldset>{onDesign&&<button className="text-link" onClick={onDesign}>{t('Design your own fly')}</button>}
 </section>
}
