import {FrozenSubjects} from './FrozenSubjects'
import {ProbeScene3D} from './ProbeScene3D'
import {adaptProbeScene} from './probeScene'
import {savedFlyLabel} from '../../shared/flyIdentity'
import {useEffect,useMemo,useState} from 'react'
import {FlaskConical,RefreshCw,Play,Pause,ArrowUpRight} from 'lucide-react'
import {api,newRequestKey} from '../../api'
import type {Fly,Identity} from '../../types'
import type {Experiment,ExperimentSubject,ProbeReport,ResearchCatalog,SubjectRole} from '../../shared/research'
import {alignment,finite,metricUnit,parseSeeds,roleStyles,sampleAt,validateHorizon,designRoleLabel,plotTransform} from '../../shared/research'
import {useI18n} from '../../shared/i18n'
import {reconcileDesignSelection,type DesignSelection} from './designSelection'

type ExperimentSummary=Pick<Experiment,'id'|'owner'|'status'|'spec'>

export function PhenotypeLab({flies,identity,selected,experimentId,onExperiment,onLogin}:{flies:Fly[];identity:Identity|null;selected:string;experimentId:string;onExperiment:(id:string)=>void;onLogin:()=>void}){
 const {t}=useI18n();const [catalog,setCatalog]=useState<ResearchCatalog|null>(null);const [experiments,setExperiments]=useState<ExperimentSummary[]>([]);const [experiment,setExperiment]=useState<Experiment|null>(null);const [probe,setProbe]=useState('gradient-v2');const [selection,setSelection]=useState<DesignSelection>(()=>reconcileDesignSelection(undefined,flies,selected,identity?.id));const [seeds,setSeeds]=useState('42');const [horizon,setHorizon]=useState(3);const [seed,setSeed]=useState(42);const [time,setTime]=useState(0);const [playing,setPlaying]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [trace,setTrace]=useState('drive_left');
 const resolvedSelection=reconcileDesignSelection(selection,flies,selected,identity?.id);
 if(resolvedSelection!==selection)setSelection(resolvedSelection);
 const design=resolvedSelection.design;
 const setDesign=(design:string)=>setSelection({...resolvedSelection,design});
 useEffect(()=>{let active=true;api<ResearchCatalog>('/research/catalog').then(c=>{if(active){setCatalog(c);if(c.probes.length)setProbe(c.probes[0].id)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 useEffect(()=>{let active=true;const refresh=()=>api<ExperimentSummary[]>('/experiments?summary=true',{},identity).then(xs=>{if(active){setExperiments(xs);}}).catch(e=>{if(active)setError(e.message)});refresh();const timer=setInterval(refresh,5000);return()=>{active=false;clearInterval(timer)}},[identity,experimentId,onExperiment]);
 useEffect(()=>{setExperiment(null);setTime(0);setPlaying(false);setError('');if(!experimentId)return;let active=true;let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const e=await api<Experiment>('/experiments/'+encodeURIComponent(experimentId),{},identity);if(!active)return;setExperiment(e);setSeed(s=>e.spec.seeds.includes(s)?s:e.spec.seeds[0]);if(e.status==='queued'||e.status==='running')timer=setTimeout(poll,2500)}catch(e){if(active){setError(String(e));timer=setTimeout(poll,5000)}}};poll();return()=>{active=false;clearTimeout(timer)}},[experimentId,identity]);
 const subjects=experiment?.subjects||[];const reports=useMemo(()=>experiment?.reports.filter(r=>r.seed===seed&&subjects.some(s=>s.fly_id===r.fly_id&&s.artifact_id===r.artifact_id))||[],[experiment,seed]);const matched=alignment(reports,subjects);const end=experiment?.spec.duration_seconds||horizon;
 useEffect(()=>{if(!playing)return;let previous=performance.now();let handle:number;const tick=(now:number)=>{const dt=(now-previous)/1000;previous=now;setTime(value=>{if(value+dt>=end){setPlaying(false);return end}return value+dt});handle=requestAnimationFrame(tick)};handle=requestAnimationFrame(tick);return()=>cancelAnimationFrame(handle)},[playing,end]);
 const keys=[...new Set(reports.flatMap(r=>Object.keys(r.metrics||{})))];const traceKeys=[...new Set(reports.flatMap(r=>(r.neural_trace||[]).flatMap(p=>Object.keys(p).filter(k=>k!=='time'&&finite(p[k])))))];
 async function run(){if(!identity){onLogin();return}setLoading(true);setError('');try{const seedSet=parseSeeds(seeds);validateHorizon(horizon);const e=await api<Experiment>('/experiments',{method:'POST',headers:{'Idempotency-Key':newRequestKey()},body:JSON.stringify({fly_id:design,probe_id:probe,seeds:seedSet,duration_seconds:horizon})},identity);setExperiments(xs=>[{id:e.id,owner:e.owner,status:e.status,spec:e.spec},...xs.filter(x=>x.id!==e.id)]);onExperiment(e.id)}catch(e){setError(e instanceof Error?t(e.message):String(e))}finally{setLoading(false)}}
 const roleName=(role:SubjectRole)=>t(role==='wildtype'?'Wild Type':role==='official'?'Official release':designRoleLabel(experiment?.owner,identity?.id));
 return <div className="phenotype-lab">
  <section className="panel lab-intro"><div><div className="eyebrow">{t('PHENOTYPE LAB')}</div><h2>{t('Three subjects. One frozen protocol.')}</h2><p>{t('Independent solo trials share the probe, seed, body, backend and horizon. Comparisons do not enter the match leaderboard.')}</p></div><span className={'availability '+(catalog?.profile.ready?'ready':'')}>{catalog?.profile.ready?t('Profile ready'):t('Profile unavailable')}</span></section>
  {catalog?.profile.limitations?.length&&<section className="panel profile-reason"><strong>{t('Scientific limitations')}</strong><ul>{catalog.profile.limitations.map(reason=><li key={reason}>{t(reason)}</li>)}</ul>{!!catalog.profile.unavailable?.length&&<p>{t('Unavailable')}: {catalog.profile.unavailable.join(', ')}</p>}</section>}
  {catalog?.profile.reason&&<p className="profile-reason panel" role="status">{t('Profile status reason')}: {catalog.profile.reason}</p>}
  <section className="panel experiment-controls"><label>{t('Experiment')}<select aria-label={t('Experiment')} value={experimentId} onChange={e=>onExperiment(e.target.value)}><option value="">{t('Select an experiment')}</option>{experiments.map(e=><option key={e.id} value={e.id}>{e.id.slice(0,12)} · {e.spec.probe_id} · {t(e.status)}</option>)}{experimentId&&!experiments.some(e=>e.id===experimentId)&&<option value={experimentId}>{experimentId.slice(0,12)}</option>}</select></label><label>{t('Saved design')}<select aria-label={t('Saved design')} value={design} onChange={e=>setDesign(e.target.value)}><option value="">{t('Select a saved design')}</option>{flies.filter(f=>f.owner===identity?.id).map(f=><option key={f.id} value={f.id} title={`${f.name} · ${f.id}`}>{savedFlyLabel(f,identity?.id,t)}</option>)}</select></label><label>{t('Probe')}<select aria-label={t('Probe')} value={probe} onChange={e=>setProbe(e.target.value)} disabled={!catalog?.probes.length}>{catalog?.probes.length?catalog.probes.map(p=><option key={p.id} value={p.id}>{p.id} · {t(p.name)}</option>):<option value={probe}>{t('Unavailable')}</option>}</select></label><label>{t('Seed set')}<input aria-label={t('Seed set')} value={seeds} onChange={e=>setSeeds(e.target.value)} placeholder="42, 43, 44"/></label><label>{t('Horizon (s)')}<input aria-label={t('Horizon (s)')} type="number" min={1} max={30} value={horizon} onChange={e=>setHorizon(+e.target.value)}/></label><button className="primary" disabled={loading||!catalog?.profile.ready||!design} onClick={run}><FlaskConical size={16}/>{t('Run comparison')}</button></section>
  {error&&<div className="error-banner" role="alert">{t('Research service unavailable')}: {error}<button aria-label={t('Retry')} onClick={()=>{setError('');api<ResearchCatalog>('/research/catalog').then(setCatalog).catch(e=>setError(e.message))}}><RefreshCw size={15}/></button></div>}
  {catalog&&<details className="panel profile-details"><summary>{t('Scientific profile and capabilities')} · <code>{catalog.profile.id}</code></summary><div className="profile-grid">{['backend_id','model_id','sensor_id','readout_id','embodiment_id','motor_id','protocol_id'].map(k=><div key={k}><small>{k}</small><code>{String(catalog.profile[k as keyof typeof catalog.profile]??t('Not supplied'))}</code></div>)}</div><p>{t('Unqualified capabilities are unavailable. A ready profile does not establish behavioral improvement.')}</p><div className="capabilities-grid">{(Array.isArray(catalog.profile.capabilities)?catalog.profile.capabilities.map(k=>[k,true] as const):Object.entries(catalog.profile.capabilities)).map(([key,value])=><div key={key}><code>{key}</code><span>{catalog.profile.ready&&(value===true||(typeof value==='object'&&value!==null&&(value as {available?:boolean}).available===true&&(value as {qualified?:boolean}).qualified!==false))?t('Reported available'):t('Unavailable')}</span>{typeof value==='object'&&value!==null&&'reason' in value&&<p>{String(value.reason)}</p>}</div>)}</div><details><summary>{t('Dependency hashes')}</summary><pre>{JSON.stringify(catalog.profile.hashes,null,2)}</pre></details></details>}
  {!experiment?<section className="panel empty-large"><FlaskConical size={36}/><h3>{experimentId?t('Loading experiment…'):t('Start with a saved design')}</h3><p>{t('Save a design to schedule a comparison, or choose a previous experiment. No measurements are invented while reports are pending.')}</p></section>:<>
   <div className="experiment-status" role="status"><span className={'state-pill '+experiment.status}>{t(experiment.status)}</span><code>{experiment.id}</code><span>{experiment.spec.probe_id} · {experiment.spec.duration_seconds} s · {t('Seeds')}: {experiment.spec.seeds.join(', ')}</span></div>{experiment.error&&<div className="error-banner" role="alert">{experiment.error}</div>}
   <FrozenSubjects subjects={subjects} owner={experiment.owner} viewer={identity?.id}/>
   <section className="panel comparison-stage"><div className="panel-heading"><span>{t('Time-aligned trajectory overlay')}</span><label>{t('Seed')} <select aria-label={t('Comparison seed')} value={seed} onChange={e=>{setSeed(+e.target.value);setTime(0);setPlaying(false)}}>{experiment.spec.seeds.map(s=><option key={s} value={s}>{s}</option>)}</select></label></div><div className="plot-legend">{subjects.map(s=><span key={s.role}><svg width="30" height="12"><path d="M0 6H30" stroke={roleStyles[s.role].color} strokeWidth="2" strokeDasharray={roleStyles[s.role].dash}/></svg>{roleStyles[s.role].symbol} {roleName(s.role)} · {s.name}</span>)}</div><ProbeScene3D reports={reports} subjects={subjects} seed={seed} time={time} fallback={<TrajectoryOverlay reports={reports} subjects={subjects} time={time}/>}/><p className="plot-note">{t(matched==='matched'?'Verified reports share conditions and time grid.':matched==='mismatch'?'Condition or time-grid mismatch. Paired inference is unavailable.':'Awaiting complete, receipted trials for all frozen subjects.')}</p><div className="playback"><button aria-label={t(playing?'Pause':'Play')} onClick={()=>{if(time>=end)setTime(0);setPlaying(!playing)}} disabled={!reports.some(r=>r.trajectory?.length)}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><span>{time.toFixed(2)} s</span><input aria-label={t('Shared time scrubber')} type="range" min="0" max={end} step=".01" value={time} onChange={e=>{setPlaying(false);setTime(+e.target.value)}}/><span>{end} s</span></div></section>
   <section className="panel metrics-panel"><div className="panel-heading"><span>{t('Measurements and paired deltas vs WT')}</span><small>{t('A zero delta is a null effect, not an improvement.')}</small></div><p className="table-note">{t('Null latency is missing or censored; the server censor flag, when supplied, is shown as its own metric. No failed trial is filled with zero.')}</p><div className="table-scroll"><table><thead><tr><th>{t('Metric')}</th><th>{t('Unit')}</th>{subjects.map(s=><th key={s.role}>{roleName(s.role)}</th>)}{subjects.filter(s=>s.role!=='wildtype').map(s=><th key={s.role}>Δ {roleName(s.role)} − WT</th>)}</tr></thead><tbody>{keys.map(key=><tr key={key}><th><code>{key}</code></th><td>{metricUnit(key)}</td>{subjects.map(s=><td key={s.role}>{metricValue(reports.find(r=>r.fly_id===s.fly_id)?.metrics?.[key],key,t)}</td>)}{subjects.filter(s=>s.role!=='wildtype').map(s=><td key={s.role}>{matched==='matched'?metricValue(experiment.comparison?.paired.find(p=>p.seed===seed&&p.fly_id===s.fly_id&&p.reference_fly_id===subjects.find(x=>x.role==='wildtype')?.fly_id)?.deltas?.[key],key,t,true):t('Unavailable')}</td>)}</tr>)}{!keys.length&&<tr><td colSpan={2+subjects.length*2}>{t('Measurements pending / unavailable')}</td></tr>}</tbody></table></div></section>
   <section className="panel paired-seeds"><div className="panel-heading">{t('Paired results across the seed set')}</div><div className="table-scroll"><table><thead><tr><th>{t('Seed')}</th><th>{t('Subject')}</th><th>{t('Trajectory divergence (mm)')}</th><th>{t('Paired metric deltas vs WT')}</th></tr></thead><tbody>{experiment.comparison?.paired?.map((pair,i)=>{const valid=alignment(experiment.reports.filter(r=>r.seed===pair.seed),subjects)==='matched';return <tr key={i}><td>{pair.seed}</td><td>{subjects.find(s=>s.fly_id===pair.fly_id)?.name||pair.fly_id}</td><td>{valid?metricValue(pair.trajectory_divergence_mm,'divergence',t):t('Unavailable')}</td><td>{valid?Object.entries(pair.deltas).map(([k,v])=><div key={k}><code>{k}</code>: {metricValue(v,k,t,true)} {metricUnit(k)}</div>):t('Condition mismatch')}</td></tr>})}{!experiment.comparison?.paired?.length&&<tr><td colSpan={4}>{t('Paired results pending / unavailable')}</td></tr>}</tbody></table></div></section>
   <section className="panel neural-comparison"><div className="panel-heading"><span>{t('Neural and drive trace comparison')}</span><select aria-label={t('Trace channel')} value={traceKeys.includes(trace)?trace:traceKeys[0]||''} onChange={e=>setTrace(e.target.value)}>{traceKeys.length?traceKeys.map(k=><option key={k}>{k}</option>):<option>{t('Unavailable')}</option>}</select></div><TracePlot reports={reports} subjects={subjects} channel={traceKeys.includes(trace)?trace:traceKeys[0]||''} time={time} end={end}/><p className="table-note">{t('Population rates are in Hz; drive channels use controller units. Activity alone is not evidence of better behavior.')}</p></section>
   <section className="panel receipts"><div className="panel-heading">{t('Trial receipts and frozen conditions')}</div>{experiment.reports.map((r,i)=><details key={i}><summary>{r.seed} · {subjects.find(s=>s.fly_id===r.fly_id)?.name||r.fly_id} · {t(r.status)} <ArrowUpRight size={13}/></summary><dl><dt>{t('Receipt SHA-256')}</dt><dd>{r.receipt_sha256||t('Unavailable')}</dd><dt>{t('Condition key')}</dt><dd>{r.condition_key||t('Unavailable')}</dd></dl><pre>{JSON.stringify({artifact_id:r.artifact_id,profile:r.profile,condition_key:r.condition_key},null,2)}</pre></details>)}</section>
  </>}
 </div>
}
function metricValue(value:unknown,key:string,t:(key:string)=>string,delta=false){if(!finite(value))return t(/latency/.test(key)?'Missing / censored':'Unavailable');if(delta&&value===0)return '0 · '+t('Null effect');if(!delta&&key==='branch_choice'&&value===0)return '0 · '+t('No choice');return (delta&&value>0?'+':'')+Number(value.toFixed(5)).toLocaleString()}
function TrajectoryOverlay({reports,subjects,time}:{reports:ProbeReport[];subjects:ExperimentSubject[];time:number}){
 const {t}=useI18n();const scene=adaptProbeScene(reports,subjects,reports[0]?.seed).geometry||undefined;const points=reports.flatMap(r=>r.trajectory||[]).filter(p=>finite(p.x)&&finite(p.y));if(!points.length)return <div className="plot-empty">{t('Trajectory pending / unavailable')}</div>;
 const {x0,x1,y0,y1,scale,sx,sy}=plotTransform(points,scene);
 return <><svg className="trajectory-svg" viewBox="0 0 720 440" role="img" aria-label={t('Trajectory comparison')} data-physical-scale={scale}><defs><pattern id="lab-grid" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="currentColor" opacity=".12"/></pattern></defs><rect x="35" y="20" width="650" height="390" rx="8" fill="url(#lab-grid)" stroke="currentColor" opacity=".5"/>
 {scene&&<rect className="scene-boundary" x={sx(-scene.size/2)} y={sy(scene.size/2)} width={scene.size*scale} height={scene.size*scale} fill="none" stroke="currentColor" opacity=".6"/>}
 {scene?.obstacles?.map((o,i)=><rect className="scene-obstacle" key={i} x={sx(o.position[0]-o.size[0]/2)} y={sy(o.position[1]+o.size[1]/2)} width={o.size[0]*scale} height={o.size[1]*scale} fill="#8c998a" stroke="#bdcbbb" opacity=".7"><title>{t('Wall')} {i+1}</title></rect>)}
 {scene?.food?.map(f=><g className="scene-food" key={f.id} transform={`translate(${sx(f.position[0])},${sy(f.position[1])})`}><circle r="7" fill="#e58f65" stroke="#ffe4ca"/><path d="M-10 0H10M0 -10V10" stroke="#ffe4ca"/><title>{t('Food source')} · {f.id} · ({f.position.slice(0,2).join(', ')}) mm · {t('Initial amount')}: {f.initial}</title><text x="12" y="-10">{t('Food source')}</text></g>)}
 {scene?.spawns?.map((p,i)=><path className="scene-spawn" key={i} d={`M${sx(p[0])-5} ${sy(p[1])-5}l10 10m-10 0l10 -10`} stroke="currentColor"><title>{t('Spawn')} {i+1}</title></path>)}
 <text x="45" y="432">x / y · mm · {t('Equal physical scale')}</text>{subjects.map((s,i)=>{const r=reports.find(r=>r.fly_id===s.fly_id&&r.artifact_id===s.artifact_id);const ps=r?.trajectory?.filter(p=>finite(p.x)&&finite(p.y)&&finite(p.time))||[];if(!ps.length)return null;const style=roleStyles[s.role],start=ps[0],last=ps[ps.length-1],at=sampleAt(ps,time);return <g key={s.role} stroke={style.color} fill="none"><polyline className="full-trajectory" points={ps.map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ')} strokeWidth="2" opacity=".5" strokeDasharray={style.dash}/><polyline points={[...ps.filter(p=>p.time<=time),...(at?[at]:[])].map(p=>`${sx(p.x)},${sy(p.y)}`).join(' ')} strokeWidth="2.5" strokeDasharray={style.dash}/><circle cx={sx(start.x)} cy={sy(start.y)} r={4+i*2}/><rect x={sx(last.x)-3-i} y={sy(last.y)-3-i} width={6+i*2} height={6+i*2}/>{at&&<><circle cx={sx(at.x)} cy={sy(at.y)} r={5+i*2} fill="#22342e"/><text stroke="none" fill={style.color} x={Math.min(600,sx(at.x)+12)} y={Math.max(35,sy(at.y)-16+i*17)}>{style.symbol} {s.role==='wildtype'?'WT':s.role==='official'?t('Official'):t('Design')}</text></>}</g>})}<text x="45" y="38">{x0.toFixed(1)}…{x1.toFixed(1)} mm / {y0.toFixed(1)}…{y1.toFixed(1)} mm</text></svg><p className="plot-note">{t('Open marker: start. Square: end. Large marker: shared time.')} {scene?t('Scene from the recorded trial receipt. Food markers show the initial source, not remaining food.'):t('Geometry unavailable; axes fit the reported positions only.')}</p></>
}
function TracePlot({reports,subjects,channel,time,end}:{reports:ProbeReport[];subjects:ExperimentSubject[];channel:string;time:number;end:number}){const {t}=useI18n();const values=reports.flatMap(r=>(r.neural_trace||[]).map(p=>p[channel]).filter(finite));if(!values.length)return <div className="empty">{t('Neural trace pending / unavailable')}</div>;const lo=Math.min(0,...values),hi=Math.max(...values,lo+1);return <div className="trace-plot"><svg viewBox="0 0 720 170" role="img" aria-label={t('Neural trace comparison')}><text x="8" y="16">{hi.toFixed(2)}</text><text x="8" y="146">{lo.toFixed(2)}</text>{subjects.map(s=>{const ps=reports.find(r=>r.fly_id===s.fly_id)?.neural_trace||[];return <polyline key={s.role} fill="none" stroke={roleStyles[s.role].color} strokeWidth="2" strokeDasharray={roleStyles[s.role].dash} points={ps.filter(p=>finite(p.time)&&finite(p[channel])).map(p=>`${50+p.time/end*650},${145-((p[channel] as number)-lo)/(hi-lo)*125}`).join(' ')}/>})}<path d={`M${50+time/end*650} 15v130`} stroke="currentColor" strokeDasharray="2 3"/><text x="50" y="165">0 s</text><text x="660" y="165">{end} s</text></svg><div className="plot-legend">{subjects.map(s=>{const ps=reports.find(r=>r.fly_id===s.fly_id)?.neural_trace||[];const p=ps.filter(p=>p.time<=time).at(-1);return <span key={s.role}>{roleStyles[s.role].symbol} {s.name}: {finite(p?.[channel])?(p![channel] as number).toFixed(3)+' @ '+p!.time.toFixed(2)+' s':t('Unavailable')}</span>})}</div></div>}
