import {useEffect,useState,useId} from 'react'
import {api} from '../../api'
import {Plus,Trash2} from 'lucide-react'
import type {CellSelector,InterventionSpec} from '../../shared/research'
import type {Report,Spec} from '../../types'
import {useI18n} from '../../shared/i18n'
export function AdvancedInterventions({value,onChange,report,spec,onValidate,busy}:{value:InterventionSpec[];onChange:(value:InterventionSpec[])=>void;report:Report|null;spec:Spec;onValidate:()=>void;busy:boolean}){
 const {t}=useI18n();function patch(index:number,side:'pre'|'post',field:keyof CellSelector,text:string){const next=value.map((v,i)=>{if(i!==index)return v;const selector={...v.selector};const cell={...selector[side]};if(text.trim())Object.assign(cell,{[field]:field==='ids'?text.split(/[,\s]+/).filter(Boolean):text});else delete cell[field];if(Object.keys(cell).length)selector[side]=cell;else delete selector[side];return {...v,selector}});onChange(next)}
 return <section className="panel advanced-editor"><div className="panel-heading"><span>{t('Advanced interventions')}</span><button className="secondary" onClick={()=>onChange([...value,{selector:{},scale:1}])}><Plus size={14}/>{t('Add intervention')}</button></div><div className="advanced-body"><p>{t('Selectors resolve against pinned connectome metadata. Exact canonical neuron IDs only; empty selectors, unknown annotations and unsupported ROI are rejected by the server.')}</p><p>{t('Absolute multipliers apply to the canonical graph; the parent records lineage, not an extra multiplication.')}</p><div className="version-strip"><span>{t('Version')}: <code>{spec.schema_version} · {spec.model_profile}</code></span><span>{t('Parent lineage')}: <code>{spec.parent_id||t('None')}</code></span><span>{t('Connectome')}: <code title={spec.connectome_sha256}>{spec.connectome_sha256.slice(0,16)||t('Unavailable')}</code></span></div>
 {value.map((item,index)=><fieldset key={index} className="intervention"><legend>{t('Intervention')} {index+1}</legend><div className="intervention-selectors">{(['pre','post'] as const).map(side=><div key={side}><h4>{t(side==='pre'?'Presynaptic selector':'Postsynaptic selector')}</h4><div className="selector-fields">{(['class','type'] as const).map(field=><label key={field}>{t(field==='class'?'Cell class':'Cell type')}<AnnotationInput field={field} label={`${t('Intervention')} ${index+1} ${side} ${field}`} value={item.selector[side]?.[field]||''} onChange={text=>patch(index,side,field,text)}/></label>)}<label>{t('Side')}<AnnotationInput field="side" label={`${t('Intervention')} ${index+1} ${side} side`} value={item.selector[side]?.side||''} onChange={text=>patch(index,side,'side',text)}/></label><label className="canonical-ids">{t('Canonical neuron IDs')}<CanonicalIds label={`${t('Intervention')} ${index+1} ${side} IDs`} value={item.selector[side]?.ids||[]} onChange={text=>patch(index,side,'ids',text)} placeholder={t('Comma or space separated exact IDs')}/></label></div></div>)}</div><div className="intervention-scale"><label>{t('Multiplier')}<input aria-label={`${t('Intervention')} ${index+1} ${t('Multiplier')}`} type="number" min="0.5" max="2" step="0.01" value={item.scale} onChange={e=>onChange(value.map((v,i)=>i===index?{...v,scale:Number(e.target.value)}:v))}/></label><button className="secondary" onClick={()=>onChange(value.filter((_,i)=>i!==index))}><Trash2 size={14}/>{t('Remove')}</button></div></fieldset>)}
 {!value.length&&<div className="empty">{t('No advanced interventions. Existing circuit and edge edits remain in the full specification.')}</div>}
 <button className="secondary" onClick={onValidate} disabled={busy}>{t('Validate metadata and preview effect')}</button><div className="compiler-preview" aria-live="polite">{[['Structural changed edges',report?.changed_edges],['Effective changed edges',report?.effective_changed_edges],['Affected neurons',report?.affected_neurons],['Synaptic contacts',report?.synaptic_contacts],['Budget used',report?.budget_used],['Budget limit',report?.budget_limit]].map(([label,n])=><div key={String(label)}><small>{t(String(label))}</small><strong>{typeof n==='number'?n.toLocaleString():t('Not validated')}</strong></div>)}</div>{report?.interventions&&<details><summary>{t('Intervention resolution details')}</summary><pre>{JSON.stringify(report.interventions,null,2)}</pre></details>}</div></section>
}

function CanonicalIds({label,value,onChange,placeholder}:{label:string;value:string[];onChange:(text:string)=>void;placeholder:string}){const [text,setText]=useState(value.join(", "));useEffect(()=>{if(JSON.stringify(text.split(/[,\s]+/).filter(Boolean))!==JSON.stringify(value))setText(value.join(", "))},[value]);return <textarea aria-label={label} value={text} placeholder={placeholder} onChange={e=>{setText(e.target.value);onChange(e.target.value)}}/>}

// Discovery is advisory. The compiler remains the authority for exact selectors.
function AnnotationInput({field,label,value,onChange}:{field:'class'|'type'|'side';label:string;value:string;onChange:(value:string)=>void}){
 const {t}=useI18n();const id=useId();const [result,setResult]=useState<{field:string;items:{value:string;count:number}[];metadata_sha256:string;total:number}|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setResult(null);const timer=setTimeout(()=>{api<NonNullable<typeof result>>('/connectome/annotations?'+new URLSearchParams({field,q:value,limit:'50'}),{signal:controller.signal}).then(data=>{if(!controller.signal.aborted){setResult(data);setLoading(false)}}).catch(e=>{if(!controller.signal.aborted){setError(e.message);setLoading(false)}})},200);return()=>{clearTimeout(timer);controller.abort()}},[field,value]);
 return <div className="annotation-discovery"><input aria-label={label} list={id} value={value} maxLength={128} onChange={e=>onChange(e.target.value)} placeholder={t('Search exact pinned annotations')}/><datalist id={id}>{result?.items.filter(item=>field!=='side'||item.value==='L'||item.value==='R').map(item=><option key={item.value} value={item.value}>{item.count.toLocaleString()} {t('neurons')}</option>)}</datalist><small aria-live="polite">{loading?t('Loading annotations…'):error?t('Annotation discovery unavailable')+': '+error:result?`${result.items.length} / ${result.total} · ${t('Suggestions with neuron counts')}`:''}</small>{result&&<details className="annotation-evidence"><summary>{t('Metadata SHA-256 and suggestions')}</summary><code className="metadata-hash">{result.metadata_sha256}</code><div className="annotation-options">{result.items.map(item=><button key={item.value} type="button" disabled={field==='side'&&item.value!=='L'&&item.value!=='R'} title={field==='side'&&item.value!=='L'&&item.value!=='R'?t('This metadata side is not supported by the intervention selector.'):undefined} onClick={()=>onChange(item.value)}>{item.value} · {item.count.toLocaleString()}</button>)}</div></details>}</div>
}
