import assert from 'node:assert/strict'
import {mkdir,writeFile} from 'node:fs/promises'
import {flies,spec,validation,experiment,cases,catalog} from './ui-fixtures.mjs'
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/tmp/fly-arena-browser-qa/node_modules/playwright/index.mjs');
const output=process.env.QA_OUTPUT||'/tmp/fly-ui-qa';await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1100},locale:'en-US',colorScheme:'light'});const page=await context.newPage();const errors=[];const calls=[];const checks=[];page.on('pageerror',e=>errors.push(e.message));let rejectMatch=false;let authMode='nyxid';let saved=null;let matchRequest=null;let tournamentRequest=null;let annotations=[];let list=[...cases];
const replay={id:'TEST-replay',status:'verified',progress:1,attempt:1,created:0,error:null,request:{fly_ids:['TEST-wt','TEST-design'],map_id:'TEST-arena',mode:'contest',seed:42,duration_seconds:3},result:{winner_slot:null,scores:[0,0],outcome:'draw',receipt_sha256:'TEST-replay-receipt'}};
const replayScene={body:{meshes:{},geoms:[]},size:12,obstacles:[],food:[],flies:[{id:'TEST-wt',name:'TEST Wild Type',color:'mint'},{id:'TEST-design',name:'TEST Design',color:'mint'}]};
const replayFrames=[0,1,2,3].map(time=>({tick:time,time,poses:[],positions:[[-2,time,0],[2,-time,0]],scores:[0,0]}));
// All fixture mutations are intercepted, never sent to the local backend.
await page.route('**/api/v1/**',async route=>{const req=route.request(),path=new URL(req.url()).pathname.replace('/api/v1','');const method=req.method();calls.push({path,method});const reply=(body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
 if(path==='/auth/config')return reply({mode:authMode,nyxid_enabled:false,login_url:null,local_registration_enabled:false});
 if(path==='/me'){assert.equal(req.headers().authorization,'Bearer TEST-cached-token');return reply({id:'TEST-owner',name:'TEST verified owner'})}
 if(path==='/auth/session')return reply({authenticated:true,user:{id:'TEST-owner',name:'TEST owner'},csrf_token:'TEST-csrf'});
 if(path==='/auth/agent-tokens')return reply([]);
 if(path==='/season')return reply({default_bridge_profile:'legacy-v1',match_profiles:[{id:'legacy-v1',name:'TEST Legacy',ready:true},{id:'sensorimotor-research-v2',name:'TEST v2',ready:true}],id:'TEST-season',name:'TEST',connectome:{sha256:'test-connectome',neuron_count:100,edge_count:1000,synaptic_contacts:2000,circuits:[{id:'olfactory',label:'嗅觉输入',name:'ORN',color:'#dca85c',neuron_count:20,edge_count:100},{id:'memory',label:'蘑菇体',name:'MB',color:'#aaa1cf',neuron_count:20,edge_count:100}]},budget:{points:100},invite_required:false,runtime_sha256:'TEST-runtime'});
 if(path==='/maps')return reply([{id:'TEST-arena',name:'测试竞技场',english:'TEST Arena',size:12,color:'#ddd',obstacles:[],food:[],modes:['contest','forage']}]);
 if(path==='/leaderboard'||path==='/training')return reply([]);
 if(path==='/matches'&&method==='GET')return reply([replay]);
 if(path==='/matches'&&method==='POST'){matchRequest=req.postDataJSON();if(rejectMatch)return reply({detail:'TEST v2 qualification unavailable'},409);return reply({...replay,id:'TEST-new-match',status:'queued',request:matchRequest})}
 if(path==='/tournaments'&&method==='POST'){tournamentRequest=req.postDataJSON();return reply({id:'TEST-tournament',matches:[replay]})}
 if(path==='/connectome/annotations'){const params=new URL(req.url()).searchParams;assert.equal(params.get('limit'),'50');annotations.push(Object.fromEntries(params));const field=params.get('field');return reply({field,items:field==='side'?[{value:'L',count:20},{value:'M',count:10}]:[{value:field==='class'?'olfactory':'TEST-cell-type',count:20}],metadata_sha256:'TEST-actual-response-metadata-hash',total:1})}
 if(path==='/matches/TEST-replay/scene')return reply(replayScene);
 if(path==='/matches/TEST-replay/frames')return reply(replayFrames);
 if(path==='/research/catalog')return reply(catalog);
 if(path==='/flies'&&method==='GET')return reply(flies);
 if(path==='/flies/validate'){assert.equal(req.headers()['x-arena-csrf'],'TEST-csrf');return reply(validation)}
 if(path==='/flies'&&method==='POST'){saved=req.postDataJSON();assert.equal(req.headers()['x-arena-csrf'],'TEST-csrf');return reply({...flies[2],spec:saved,experiment_id:null})}
 if(path==='/experiments'&&method==='GET')return reply(list);
 if(path==='/experiments'&&method==='POST'){assert.ok(req.headers()['idempotency-key']);assert.equal(req.headers()['x-arena-csrf'],'TEST-csrf');const e={...experiment,id:'TEST-new',status:'queued',spec:req.postDataJSON(),reports:[],comparison:null};list=[e,...list];return reply(e)}
 if(path.startsWith('/experiments/'))return reply(list.find(e=>e.id===path.split('/').at(-1))||{},list.some(e=>e.id===path.split('/').at(-1))?200:404);
 // Keep the real anatomical preview, season, maps and legacy replays read-only.
 if(method!=='GET')throw Error('Unexpected mutation '+path);
 return route.continue();
});
try{
 await page.goto(process.env.QA_BASE_URL||'http://127.0.0.1:5174');await page.getByLabel('Language',{exact:true}).selectOption('en');await page.getByLabel('Appearance',{exact:true}).selectOption('dark');assert.equal(await page.locator('.fly-card.selected').count(),0);assert.ok(await page.getByText('Unsaved canonical draft',{exact:true}).count());assert.equal(await page.locator('.exploratory-controls').getAttribute('open'),null);await page.getByRole('button',{name:'Phenotype Lab',exact:true}).click();await page.getByLabel('Experiment',{exact:true}).selectOption('TEST-complete');await page.locator('.trajectory-svg').waitFor();assert.equal(await page.locator('.subject-card').count(),3);assert.equal(await page.locator('.trajectory-svg polyline').count(),6);assert.ok(await page.getByText('Missing / censored',{exact:true}).count());assert.ok(await page.getByText('0 · Null effect',{exact:true}).count());assert.equal(await page.locator('.paired-seeds tbody tr').count(),4);assert.equal(await page.locator('.scene-food').count(),1);assert.equal(await page.locator('.scene-obstacle').count(),1);const wall=await page.locator('.scene-obstacle').evaluate(el=>({w:+el.getAttribute('width'),h:+el.getAttribute('height')}));assert.ok(Math.abs(wall.w/wall.h-2)<1e-9);assert.ok((await page.locator('.subject-card.design').innerText()).includes('Your design'));await page.locator('.profile-reason').getByText('TEST reduced mode: vision and learning unavailable',{exact:false}).waitFor();checks.push('Frozen roles, trajectories, missing latency, null effects, and all-seed paired rows');
 await page.getByLabel('Shared time scrubber').fill('1.5');assert.ok((await page.locator('.playback').innerText()).includes('1.50'));await page.getByLabel('Trace channel').selectOption('olfactory');assert.ok((await page.locator('.trace-plot').innerText()).includes('TEST Design'));checks.push('Shared scrubber and trace-channel switching');
 await page.screenshot({path:output+'/fixture-lab-dark-en.png',fullPage:true});
 await page.getByLabel('Experiment',{exact:true}).selectOption('TEST-mismatch');await page.getByText('Condition or time-grid mismatch. Paired inference is unavailable.',{exact:false}).waitFor();assert.ok((await page.locator('.metrics-panel').innerText()).includes('Unavailable'));checks.push('Mismatched conditions suppress paired inference');
 for(const state of ['queued','running','failed']){await page.getByLabel('Experiment',{exact:true}).selectOption('TEST-'+state);await page.locator('.state-pill.'+state).waitFor();assert.equal(await page.locator('.metrics-panel tbody tr').count(),state==='running'?6:1)}checks.push('Queued, partial running and failed states; no fabricated failed metrics');
 await page.getByLabel('Experiment',{exact:true}).selectOption('TEST-complete');await page.getByLabel('Seed set').fill('42, 43, 42');await page.getByRole('button',{name:'Run comparison',exact:true}).click();await page.getByText('Seeds must be distinct.',{exact:false}).waitFor();await page.getByLabel('Seed set').fill('1,2,3,4,5,6,7,8,9');await page.getByRole('button',{name:'Run comparison',exact:true}).click();await page.getByText('Enter between 1 and 8 distinct seeds.',{exact:false}).waitFor();await page.getByLabel('Seed set').fill('42, 43');await page.getByLabel('Horizon (s)').fill('31');await page.getByRole('button',{name:'Run comparison',exact:true}).click();await page.getByText('Horizon must be an integer from 1 to 30 seconds.',{exact:false}).waitFor();await page.getByLabel('Horizon (s)').fill('5');await page.getByRole('button',{name:'Run comparison',exact:true}).click();await page.locator('.state-pill.queued').waitFor();assert.deepEqual(list[0].spec.seeds,[42,43]);assert.equal(list[0].spec.duration_seconds,5);checks.push('Experiment creation sends exact seed/horizon contract and CSRF/idempotency headers');
 await page.getByRole('button',{name:'AI / API',exact:true}).click();await page.getByLabel('FlySpec JSON editor').fill(JSON.stringify(spec));await page.getByRole('button',{name:'Open in Studio',exact:true}).click();await page.getByLabel('Intervention 1 pre IDs',{exact:true}).waitFor();assert.equal(await page.getByLabel('Intervention 1 pre IDs',{exact:true}).inputValue(),'720575940123456789');await page.getByLabel('Intervention 1 post type',{exact:true}).fill('PN-edited');await page.getByLabel('Intervention 1 Multiplier',{exact:true}).fill('1.35');await page.getByRole('button',{name:'Validate metadata and preview effect',exact:true}).click();await page.locator('.compiler-preview').getByText('24',{exact:true}).waitFor();await page.getByText('Intervention resolution details',{exact:true}).click();assert.ok((await page.locator('.advanced-editor pre').innerText()).includes('matched_edges'));await page.locator('.annotation-discovery .metadata-hash').first().waitFor({state:'attached'});await page.locator('.annotation-evidence summary').first().click();await page.getByRole('button',{name:'olfactory · 20',exact:true}).first().click();assert.equal(await page.getByLabel('Intervention 1 pre class',{exact:true}).inputValue(),'olfactory');assert.ok(annotations.some(a=>a.field==='side'));assert.equal(await page.locator('datalist option[value="M"]').count(),0);assert.ok(await page.getByRole('button',{name:'M · 10',exact:true,includeHidden:true}).first().isDisabled());assert.ok((await page.locator('.metadata-hash').first().innerText()).includes('TEST-actual-response-metadata-hash'));checks.push('Advanced exact selector discovery with count/hash, bounded requests and interventions compiler detail');
 await page.getByRole('button',{name:'AI / API',exact:true}).click();await page.getByRole('button',{name:'Load current design',exact:true}).click();const exported=JSON.parse(await page.getByLabel('FlySpec JSON editor').inputValue());assert.equal(exported.interventions[0].scale,1.35);assert.equal(exported.interventions[0].selector.post.type,'PN-edited');assert.deepEqual(exported.edge_deltas,spec.edge_deltas);assert.deepEqual(exported.future_metadata,spec.future_metadata);checks.push('JSON round trip preserves interventions, edge deltas and unknown full fields');
 await page.getByRole('button',{name:'Open in Studio',exact:true}).click();await page.getByRole('button',{name:'Save fly',exact:true}).click();await page.getByLabel('Starting fly',{exact:true}).waitFor();assert.equal(await page.getByLabel('Starting fly',{exact:true}).inputValue(),'TEST-design');assert.equal(saved.interventions[0].scale,1.35);assert.deepEqual(saved.future_metadata,spec.future_metadata);assert.equal(calls.filter(c=>c.path==='/experiments'&&c.method==='POST').length,1);assert.equal(calls.filter(c=>c.path==='/training'&&c.method==='POST').length,0);checks.push('Save retains edits and opens training with the saved fly, without starting evaluations');await page.getByRole('button',{name:'Phenotype Lab',exact:true}).click();
 await page.getByLabel('Experiment',{exact:true}).selectOption('TEST-complete');await page.getByLabel('Language',{exact:true}).selectOption('zh-CN');await page.getByLabel('外观',{exact:true}).selectOption('light');await page.screenshot({path:output+'/fixture-lab-light-zh.png',fullPage:true});await page.reload();await page.getByLabel('外观',{exact:true}).waitFor();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');assert.equal(await page.locator('html').getAttribute('lang'),'zh-CN');checks.push('Locale and explicit theme persist across reload');
 await page.getByLabel('外观',{exact:true}).selectOption('system');await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');checks.push('System appearance tracks OS preference');
 await page.getByLabel('语言',{exact:true}).selectOption('en');await page.getByRole('button',{name:'Phenotype Lab',exact:true}).click();await page.getByLabel('Experiment',{exact:true}).selectOption('TEST-complete');await page.setViewportSize({width:390,height:844});await page.screenshot({path:output+'/fixture-lab-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile horizontal page overflow');checks.push('390px mobile layout has no horizontal page overflow');
 await page.getByRole('button',{name:'Design Studio',exact:true}).click();await page.screenshot({path:output+'/fixture-design-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.setViewportSize({width:1440,height:1100});await page.getByRole('button',{name:'Arena',exact:true}).click();await page.getByLabel('Match fly',{exact:true}).selectOption('TEST-design');await page.locator('.fly-world-label').first().waitFor();assert.equal(await page.locator('.fly-world-label').count(),2);assert.equal(await page.locator('.fly-world-label.selected').count(),1);assert.ok((await page.locator('.fly-world-label.selected').innerText()).includes('Your design'));await page.screenshot({path:output+'/fixture-arena-labels.png',fullPage:true});checks.push('Same-color replay subjects have floating slot/name/role labels and a separate selected outline');
 assert.equal(await page.getByLabel('Match scientific profile',{exact:true}).inputValue(),'sensorimotor-research-v2');assert.ok((await page.locator('.stage-heading').innerText()).includes('Legacy v1'));await page.getByLabel('Opponent',{exact:true}).selectOption('TEST-wt');await page.getByRole('button',{name:'Start match',exact:false}).click();await page.waitForTimeout(150);assert.equal(matchRequest.bridge_profile,'sensorimotor-research-v2');await page.getByRole('button',{name:'Create paired match series',exact:false}).click();await page.waitForTimeout(150);assert.equal(tournamentRequest.bridge_profile,'sensorimotor-research-v2');rejectMatch=true;await page.getByRole('button',{name:'Start match',exact:false}).click();await page.getByText('TEST v2 qualification unavailable',{exact:true}).waitFor();assert.equal(await page.getByLabel('Match scientific profile',{exact:true}).inputValue(),'sensorimotor-research-v2');assert.equal(matchRequest.bridge_profile,'sensorimotor-research-v2');rejectMatch=false;await page.getByLabel('Match scientific profile',{exact:true}).selectOption('legacy-v1');await page.getByRole('button',{name:'Start match',exact:false}).click();await page.waitForTimeout(150);assert.equal(matchRequest.bridge_profile,'legacy-v1');checks.push('Default ready v2, explicit match/tournament profile, rejection without fallback, legacy replay label');
 await page.evaluate(()=>{location.hash='experiment=TEST-complete'});await page.locator('.state-pill.complete').waitFor();await page.evaluate(()=>{location.hash='experiment=TEST-failed'});await page.locator('.state-pill.failed').waitFor();await page.goBack();await page.locator('.state-pill.complete').waitFor();await page.goForward();await page.locator('.state-pill.failed').waitFor();checks.push('Same-document hash changes, browser back and forward update experiment');
 authMode='local';await page.evaluate(()=>{localStorage.setItem('flyarena.identity',JSON.stringify({id:'TEST-spoof',name:'TEST stale identity',token:'TEST-cached-token'}));location.hash='experiment=TEST-complete'});await page.reload();await page.getByRole('button',{name:'TEST verified owner',exact:true}).waitFor();await page.locator('.state-pill.complete').waitFor();assert.ok((await page.locator('.subject-card.design').innerText()).includes('Your design'));list=[...list,{...experiment,id:'TEST-other-owner',owner:'TEST-another-owner'}];await page.evaluate(()=>{location.hash='experiment=TEST-other-owner'});await page.getByText('Submitted design · Frozen',{exact:false}).waitFor();checks.push('Cached local token identity verified by /me; different experiment owner displays Submitted design');
 assert.deepEqual(errors,[]);await writeFile(output+'/fixture-checks.json',JSON.stringify({notice:'UI CONTRACT FIXTURES ONLY — not scientific evidence or real end-to-end experiment',checks,errors,calls},null,2));console.log(JSON.stringify({checks,errors,output},null,2));
}finally{await browser.close()}
