"""Generate a standalone read-only HTML/SVG viewer from actual recorded arrays."""
from pathlib import Path
import json,html
import numpy as np
ROOT=Path(__file__).resolve().parents[1]; BASE=ROOT/'var/embodied-v7'; legs=['LF','LM','LH','RF','RM','RH']
def main():
    geo=json.loads((BASE/'replay/geometry.json').read_text()); subjects=json.loads((BASE/'subjects.json').read_text()); records={}
    for panel,pattern in [('replay','*-intact'),('contact','WT-*-intact')]:
        for folder in sorted((BASE/panel).glob(pattern)):
            if panel=='replay':
                name=folder.name[:-7]; a=np.load(folder/'body.npz'); z=np.load(BASE/panel/(name+'-zero')/'body.npz'); stride=10
                old=np.load(Path('/tmp/fly-arena-contact-v6/var/contact-v6/assay-001')/name/'samples.npz')
                records[panel+'/'+name]={'neuralT':(old['ticks']*.0001).tolist(),'pools':old['motor_pools_hz'].tolist(),'t':(a['ticks'][::stride]*.0001).tolist(),'knees':a['knees'][::stride].tolist(),'passive':z['knees'][::stride].tolist(),'requested':a['requested'][::stride].tolist(),'force':a['force'][::stride].tolist(),'claim':'Archived neural replay → tethered actual joints (open loop)'}
            else:
                condition=json.loads((folder/'condition.json').read_text()); a=np.load(folder/'samples.npz'); stem=folder.name.rsplit('-',1)[0]
                p=BASE/panel/(stem+'-motorzero')/'samples.npz'; z=np.load(p) if p.exists() else None
                records[panel+'/'+stem]={'neuralT':(a['ticks']*.0001).tolist(),'aff':a['afferent_spikes'].tolist(),'t':(a['ticks']*.0001).tolist(),'knees':a['knees'].tolist(),'passive':z['knees'].tolist() if z else None,'requested':a['command_rad'].tolist(),'force':a['force'].tolist(),'ratios':a['contact_ratios'].tolist(),'pools':a['pools_hz'].tolist(),'claim':'Actual contact → full connectome → tethered actual joints (closed loop; 10 ms sampling)'}
    data={'records':records,'neutral':geo['neutral_rad'],'legs':legs,'subjects':subjects,'replayGate':json.loads((BASE/'replay/gate.json').read_text()),'contactGate':json.loads((BASE/'contact/gate.json').read_text())}
    payload=json.dumps(data,separators=(',',':')).replace('<','\\u003c')
    page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Contact embodiment v7 • measured joint evidence</title>
<style>:root{color-scheme:light dark;font:16px system-ui}body{max-width:1180px;margin:36px auto;padding:0 20px}h1{font-size:28px}p{line-height:1.55}select{padding:8px;max-width:100%}svg{width:100%;background:#13202c;border-radius:8px}table{table-layout:fixed;overflow-wrap:anywhere;border-collapse:collapse;width:100%;margin:16px 0}td,th{border-bottom:1px solid #777;padding:9px;text-align:left}code{overflow-wrap:anywhere;font-size:12px}.legend{color:#27bfa5}.passive{color:#e7ae66}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:700px){.grid{grid-template-columns:1fr}}.card{padding:16px;border:1px solid #777;border-radius:8px}.warning{border-left:4px solid #e7ae66;padding:12px}</style>
<h1>Contact embodiment v7 / 接触具身实验</h1><p class="warning"><b>Tethered fixture / 固定胸部夹具.</b> These are actual simulated joint angles, with thorax fixed and 60 non-knee coordinates mechanically constrained. They are not free walking or evidence of olfactory approach. No body poses are invented here.</p>
<div id="status"></div><div id="subjects"></div><p id="coverage"></p><label>Recorded trial <select id="trial"></select></label> <label>Measured knee <select id="leg"></select></label><p id="claim"></p>
<p><span class="legend">● intact actual knee</span> · <span class="passive">● motor-output-zero actual knee</span> · pale blue: neural requested offset. Offsets are relative to registered NEUTRAL. Seed43 has no authorized matched passive trial.</p>
<div class="grid"><div><h3>Knee angle offset (rad)</h3><svg id="angle" viewBox="0 0 540 270" role="img" aria-label="Measured knee angle traces"></svg></div><div><h3>Active minus passive (rad)</h3><svg id="difference" viewBox="0 0 540 270" role="img" aria-label="Measured passive-subtracted joint response"></svg></div><div><h3>Actuator force (native torque)</h3><svg id="force" viewBox="0 0 540 270" role="img" aria-label="Measured actuator force"></svg></div><div><h3>Contact / body weight</h3><svg id="contact" viewBox="0 0 540 270" role="img" aria-label="Measured contact ratio"></svg></div><div><h3>Motor pool mean rate (Hz)</h3><svg id="neural" viewBox="0 0 540 270" role="img" aria-label="Recorded motor pool rates"></svg></div><div><h3>Own tactile afferent spikes per 10 ms</h3><svg id="afferent" viewBox="0 0 540 270" role="img" aria-label="Recorded afferent spikes"></svg></div></div>
<p id="metrics"></p><details><summary>Exact gate facts and limitations</summary><pre id="facts" style="white-space:pre-wrap"></pre></details><p>Sampling: replay 1 ms for this viewer; source records 0.1 ms. Closed loop 10 ms. Force impulse uses sampled quadrature; actuator work is a mechanical proxy. Neural-only motor authority, equal antagonist pooling, lumped nerve inputs and tether constraints are engineering assumptions. No biological reflex identification, walking admission, or original fifteen-gate qualification is claimed.</p>
<script id="data" type="application/json">PAYLOAD</script><script>
const D=JSON.parse(document.getElementById('data').textContent),$=x=>document.getElementById(x), keys=Object.keys(D.records);
$('status').textContent='Coordinate mapping: PASS · recorded-rate physical transduction: '+(D.replayGate.transduction_pass?'PASS':'FAIL')+' · actual physical contact causal gate: '+(D.contactGate.physical_causal_pass?'PASS':'FAIL');
let table=document.createElement('table');let tr=table.insertRow();for(let s of ['Role','Artifact identity','Ownership / authorship']){let th=document.createElement('th');th.textContent=s;tr.appendChild(th)}
for(let s of D.subjects){let r=table.insertRow();r.insertCell().textContent=s.role+' — '+s.spec.name;r.insertCell().textContent=s.artifact_id;r.insertCell().textContent=s.role==='design'?'Existing submitted Preview; owner '+s.owner+'; human authorship and current-user ownership not inferred':'Registry owner: '+s.owner;} $('subjects').appendChild(table);
$('coverage').textContent=D.contactGate.physical_causal_pass?'Actual subject panel recorded separately; inspect its condition receipts.':'WT physical panel only. Official Nectar and submitted Preview identities are bound and verified, but their dependent physical comparison was NOT RUN because the causal gate failed. No fabricated ABC curves.';
keys.forEach(k=>$('trial').add(new Option(k,k)));D.legs.forEach((l,i)=>$('leg').add(new Option(l,i)));$('facts').textContent=JSON.stringify({replay:D.replayGate,contact:D.contactGate},null,2);
function plot(id,t,series){let svg=$(id);svg.replaceChildren();let values=series.flatMap(s=>s.v),lo=Math.min(0,...values),hi=Math.max(0,...values);if(hi-lo<1e-9){lo-=.001;hi+=.001}let pad=(hi-lo)*.1;lo-=pad;hi+=pad;const el=(tag,attrs,text)=>{let n=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text)n.textContent=text;svg.appendChild(n);return n};let px=x=>55+465*x/t[t.length-1],py=y=>230-200*(y-lo)/(hi-lo);for(let i=0;i<5;i++){let y=lo+(hi-lo)*i/4;el('line',{x1:55,x2:520,y1:py(y),y2:py(y),stroke:'#42505e'});el('text',{x:3,y:py(y)+4,fill:'#ddd','font-size':11},y.toFixed(4))}for(let i=0;i<=5;i++)el('text',{x:px(t[t.length-1]*i/5),y:255,fill:'#ddd','font-size':11},(t[t.length-1]*i/5).toFixed(2)+'s');for(let s of series)el('polyline',{points:s.v.map((v,i)=>px(t[i])+','+py(v)).join(' '),fill:'none',stroke:s.color,'stroke-width':2});if(!series.length)el('text',{x:65,y:100,fill:'#ddd'},'No matched record for this selection');}
function draw(){let r=D.records[$('trial').value],i=+$('leg').value,n=D.neutral[i],a=r.knees.map(x=>x[i]-n),z=r.passive?.map(x=>x[i]-n),series=[{v:a,color:'#27bfa5'},{v:r.requested.map(x=>x[i]),color:'#9dd5ed'}];if(z)series.push({v:z,color:'#e7ae66'});plot('angle',r.t,series);plot('difference',r.t,z?[{v:a.map((x,j)=>x-z[j]),color:'#27bfa5'}]:[]);plot('force',r.t,[{v:r.force.map(x=>x[i]),color:'#9dd5ed'}]);plot('contact',r.t,r.ratios?[{v:r.ratios.map(x=>x[i]),color:'#e7ae66'}]:[]);plot('neural',r.neuralT,[{v:r.pools.map(x=>x[i][0]),color:'#27bfa5'},{v:r.pools.map(x=>x[i][1]),color:'#e7ae66'}]);plot('afferent',r.neuralT,r.aff?[{v:r.aff.map(x=>x[i]),color:'#9dd5ed'}]:[]);$('claim').textContent=r.claim+' · Neural plot: green flexor mean, amber extensor mean; no inferred rates.';$('metrics').textContent='Maximum absolute observed offset: '+Math.max(...a.map(Math.abs)).toFixed(8)+' rad'+(z?' · peak active-minus-passive: '+Math.max(...a.map((x,j)=>Math.abs(x-z[j]))).toFixed(8)+' rad':'');}
$('trial').onchange=$('leg').onchange=draw;draw();</script></html>'''
    (BASE/'viewer.html').write_text(page.replace('PAYLOAD',payload)); print('viewer records',len(records),'bytes',(BASE/'viewer.html').stat().st_size)
if __name__=='__main__':main()
