import React from 'react'
import ReactDOM from 'react-dom/client'
import {I18nProvider} from './shared/i18n'
import App from './App'
import './style.css'
import './features/arena/brainActivity.css'
import './features/arena/behaviorChapters.css'
import './features/arena/responseStory.css'
import './features/arena/localBrainGraph.css'
import './features/arena/anatomicalBrain.css'
import './features/arena/sharedResources.css'
import './features/arena/feedingHistory.css'
import './features/arena/replayDesign.css'
import './features/arena/replayCamera.css'
import './features/arena/replayComparison.css'
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><I18nProvider><App/></I18nProvider></React.StrictMode>)

import './features/arena/taskObservation.css'
