import {useEffect,useState} from 'react'
import {ArrowRight,BookOpen,Download,GitBranch,Play} from 'lucide-react'
import {api} from '../../api'
import type {Fly,Identity,Match} from '../../types'
import {useI18n} from '../../shared/i18n'
import {algorithmName} from '../training/algorithms'
import './life.css'
type Card={id:string;name:string;parent_id:string|null;can_annotate:boolean}
type Note={id:string;action:string;reason:string;match_id:string|null;supersedes:string|null;created:number}
type Experience={match:Match;slots:number[];scores:number[]|null;evaluation_context:string}
type LifeRecord={fly:Fly;can_annotate:boolean;origin:null|{run_id:string;strategy:string;optimizer_name:string;round:number;fitness:number|null;saved:boolean};ancestors:Card[];descendants:Card[];notes:Note[];experiences:Experience[];learning:{within_match_plasticity:string;acquired_state_inherited:boolean}}
type Observation={status:string;duration_seconds?:number;frame_count?:number;observations:null|{slot:number;model_profile?:string;food_consumed:number;food_outcome:string;first_intake_record_seconds:number|null;exit_seconds:number|null;sampled_path_mm:number;final_energy:number;total_spikes:number|null;final_neural_activity:Record<string,number>|null}[]}
// Keep browser URLs independent of personal training routes.
import {lifeHash} from './navigation'
const focus=()=>new URLSearchParams(location.hash.slice(1)).get('fly')||''
const actions=['retain','investigate','stop_exploring','hypothesis','correction']
export function LifeLedger({identity,selected,onBranch,onCompete,onReplay}:{identity:Identity|null;selected:string;onBranch:(f:Fly)=>void;onCompete:(f:Fly)=>void;onReplay:(m:Match)=>void}){
 const {locale,t}=useI18n();const c=(en:string,zh:string)=>locale==='en'?en:zh
 const [cards,setCards]=useState<Card[]>([]);const [id,setId]=useState(focus()||selected);const [record,setRecord]=useState<LifeRecord|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false)
 const [action,setAction]=useState('investigate');const [reason,setReason]=useState('');const [matchId,setMatchId]=useState('');const [supersedes,setSupersedes]=useState('');const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);const [key,setKey]=useState(()=>crypto.randomUUID());const [query,setQuery]=useState('')
 const labels:{[k:string]:string}={retain:c('Retain','保留'),investigate:c('Investigate','继续调查'),stop_exploring:c('Stop exploring','停止探索'),hypothesis:c('Hypothesis','研究假设'),correction:c('Correction','更正')}
 function open(value:string){history.pushState(null,'',lifeHash(value));setId(value)}
 useEffect(()=>{const sync=()=>setId(focus());window.addEventListener('hashchange',sync);window.addEventListener('popstate',sync);return()=>{window.removeEventListener('hashchange',sync);window.removeEventListener('popstate',sync)}},[])
 useEffect(()=>{const ctrl=new AbortController();setCards([]);api<Card[]>('/lives',{signal:ctrl.signal},identity).then(data=>{if(!ctrl.signal.aborted){setCards(data);setId(old=>old||data[0]?.id||'')}}).catch(e=>{if(!ctrl.signal.aborted)setError(String(e))});return()=>ctrl.abort()},[identity?.id,identity?.token])
 useEffect(()=>{setRecord(null);setMatchId('');setSupersedes('');setReason('');setKey(crypto.randomUUID());if(!id)return;const ctrl=new AbortController();setLoading(true);setError('');api<LifeRecord>('/lives/'+id,{signal:ctrl.signal},identity).then(data=>{if(!ctrl.signal.aborted)setRecord(data)}).catch(e=>{if(!ctrl.signal.aborted)setError(String(e))}).finally(()=>{if(!ctrl.signal.aborted)setLoading(false)});return()=>ctrl.abort()},[id,identity?.id,identity?.token,revision])
 function download(){if(!record)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'}));a.download='life-'+id+'.json';a.click();URL.revokeObjectURL(a.href)}
 async function submit(){if(!record)return;setBusy(true);setError('');try{await api('/lives/'+id+'/notes',{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify({action,reason,match_id:matchId||null,supersedes:action==='correction'?supersedes:null})},identity);setRevision(v=>v+1)}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <div className="life-layout">
  <aside className="panel life-index"><div className="panel-heading"><span><BookOpen size={17}/>{c('Life archive','生命样本档案')}</span><small>{cards.length}</small></div><input aria-label={c('Find a life','查找生命样本')} placeholder={c('Name or individual ID','名称或个体编号')} value={query} onChange={e=>setQuery(e.target.value)}/><p>{c('Public samples and your own candidates. Up to 200 recent individuals.','公开样本与你自己的候选，显示最近 200 个个体。')}</p><div>{cards.filter(f=>(f.name+' '+f.id).toLowerCase().includes(query.toLowerCase())).map(f=><button key={f.id} className={id===f.id?'selected':''} onClick={()=>open(f.id)}><strong>{f.name}</strong><small>{f.id.slice(0,8)} · {f.can_annotate?c('Your design','你的设计'):c('Public sample','公开样本')}</small></button>)}</div></aside>
  <div className="life-main">{error&&<p role="alert" className="training-error">{error}</p>}{loading&&<p role="status">{c('Loading life record…','正在加载生命档案…')}</p>}
   {record&&<>
    <section className="panel life-intro"><span className="tiny-label">LIFE / EXPERIENCE / LINEAGE</span><h2>{record.fly.name}</h2><code>{id}</code>{record.fly.spec.description&&<p>{record.fly.spec.description}</p>}<p>{c('A recorded individual, its experiences, and the decisions that shape its next branch.','一个个体、它经历过的环境，以及决定下一条分支的选择。')}</p><div className="life-actions">{record.fly.source?.kind==='published-training'?<a className="primary" href={'#tab=train&showcase='+encodeURIComponent(record.fly.source.run_id)}><GitBranch size={15}/>{c('Open source trajectory to save a copy','打开来源轨迹并保存副本')}</a>:<><button className="primary" onClick={()=>onBranch(record.fly)}><GitBranch size={15}/>{c('Continue evolution','从它继续演化')}</button><button className="secondary" onClick={()=>onCompete(record.fly)}>{c('Prepare a comparison','准备对比比赛')}<ArrowRight size={14}/></button></>}<button className="secondary" onClick={download}><Download size={14}/>{c('Export life record','导出生命档案')}</button></div><small>{c('These actions prepare a plan; only Start submits computation.','上述操作只准备方案，点击开始才会提交计算。')}</small></section>
    <section className="panel life-birth"><h3>{c('Birth and inheritance','出生与继承')}</h3><p>{record.origin?<>{t(algorithmName(record.origin.strategy))} · {record.origin.optimizer_name} · {record.origin.strategy==='random_search'?c('Search round','搜索轮次'):c('Generation','世代')} {record.origin.round}</>:c('Submitted design or reference individual. No optimizer provenance was recorded.','提交的设计或参考个体，未记录优化器来源。')}</p><div className="individual-genes">{record.fly.spec.weight_mutations.length?record.fly.spec.weight_mutations.map(w=><span key={w.selector}>{w.selector} ×{w.scale.toFixed(4)}</span>):<span>{c('Canonical circuit multipliers','标准回路倍率')}</span>}</div><p>τ ×{record.fly.spec.neuron_parameters.tau_scale} · Δthreshold {record.fly.spec.neuron_parameters.threshold_shift_mv} mV · {record.fly.spec.model_profile}</p><p>{c('The complete birth design is retained in the export, including edge and advanced edits. Within-match plasticity is off; acquired neural state is not inherited.','导出文件保留完整出生设计，包含边权及高级干预。当前比赛内可塑性未启用，后代不继承比赛结束时的神经状态。')}</p><div className="life-relations"><div><strong>{c('Ancestors · nearest first','祖先 · 从最近父代开始')}</strong>{record.ancestors.map(f=><button className="text-link" key={f.id} onClick={()=>open(f.id)}>{f.name} · {f.id.slice(0,8)}</button>)}{!record.ancestors.length&&<p>{c('No accessible ancestor recorded.','没有可访问的祖先记录。')}</p>}</div><div><strong>{c('Direct descendants','直接后代')}</strong>{record.descendants.map(f=><button className="text-link" key={f.id} onClick={()=>open(f.id)}>{f.name} · {f.id.slice(0,8)}</button>)}{!record.descendants.length&&<p>{c('No accessible descendants yet.','尚无可访问的后代。')}</p>}</div></div></section>
    <section className="panel life-experiences"><h3>{c('What actually happened','实际经历')}</h3><p>{c('Results apply to their recorded environment and duration. Different versions or conditions are separate experiments. Showing up to 100 recent experiences.','结果只适用于记录中的环境与时长。不同版本、不同条件分别视为实验，显示最近 100 次经历。')}</p>{!record.experiences.length&&<p>{c('No accessible evaluations yet.','尚无可访问的评估。')}</p>}{record.experiences.map(e=><ExperienceCard key={e.match.id} id={id} experience={e} identity={identity} onReplay={onReplay}/>)}</section>
    <section className="panel life-notes"><h3>{c('Interpretations and next choices','解释与后续选择')}</h3><p>{c('Researcher notes do not change recorded results or confer champion status. Corrections append a new note and preserve the original.','研究者笔记不修改原始成绩，也不授予冠军资格。更正通过追加新笔记完成，原文保留。')}</p>{record.origin?.saved&&<p className="life-fact">{c('Recorded action: saved from training to the fly library.','已记录操作：从训练中保存到果蝇库。')}</p>}{record.descendants.length>0&&<p className="life-fact">{c('Recorded action: used as a parent. See the descendants above.','已记录操作：被用作父代，后代见上方谱系。')}</p>}{record.notes.map(n=><article key={n.id}><strong>{labels[n.action]||n.action}</strong><small>{new Date(n.created*1000).toLocaleString(locale)}</small><p>{n.reason}</p>{n.match_id&&<code>{c('Experience','经历')} · {n.match_id.slice(0,8)}</code>}{n.supersedes&&<p>{c('Corrects note','更正笔记')} · {n.supersedes.slice(0,8)}</p>}<code>{n.id.slice(0,8)}</code></article>)}
    {record.can_annotate&&<form onSubmit={e=>{e.preventDefault();void submit()}}><label>{c('Decision or interpretation','选择或解释')}<select value={action} onChange={e=>{setAction(e.target.value);setKey(crypto.randomUUID())}}>{actions.map(a=><option key={a} value={a}>{labels[a]}</option>)}</select></label><label>{c('Related experience (optional)','关联经历（可选）')}<select value={matchId} onChange={e=>{setMatchId(e.target.value);setKey(crypto.randomUUID())}}><option value="">—</option>{record.experiences.map(e=><option key={e.match.id} value={e.match.id}>{e.match.request.map_id} · {e.match.id.slice(0,8)}</option>)}</select></label>{action==='correction'&&<label>{c('Earlier note','被更正的笔记')}<select required value={supersedes} onChange={e=>{setSupersedes(e.target.value);setKey(crypto.randomUUID())}}><option value="">—</option>{record.notes.map(n=><option key={n.id} value={n.id}>{n.id.slice(0,8)} · {n.reason.slice(0,40)}</option>)}</select></label>}<label>{c('Reason / hypothesis','理由／假设')}<textarea required maxLength={2000} value={reason} onChange={e=>{setReason(e.target.value);setKey(crypto.randomUUID())}}/></label><p>{c('Notes follow this sample’s visibility. Public samples have public notes. A private candidate’s notes become public if you save or publish it.','笔记跟随样本的可见性。公开样本的笔记也公开；私有候选被保存或发布后，其笔记随之公开。')}</p><button className="primary" disabled={busy||!reason.trim()||(action==='correction'&&!supersedes)}>{c('Append to life record','追加到生命档案')}</button></form>}
    </section>
   </>}
  </div>
 </div>
}
function ExperienceCard({id,experience:e,identity,onReplay}:{id:string;experience:Experience;identity:Identity|null;onReplay:(m:Match)=>void}){
 const {locale}=useI18n();const c=(en:string,zh:string)=>locale==='en'?en:zh
 const [data,setData]=useState<Observation|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 async function inspect(){setBusy(true);setError('');try{setData(await api<Observation>(`/lives/${id}/experiences/${e.match.id}`,{},identity))}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <article className="life-experience"><div className="life-experience-heading"><strong>{e.match.request.map_id} · {e.match.request.mode}</strong><span>{c('Score','成绩')} {e.scores===null?'—':e.scores.map(s=>s.toFixed(4)).join(' / ')}</span></div><p>{c('Seed','种子')} {e.match.request.seed} · {e.match.request.duration_seconds}s · {e.match.status} · {e.match.id.slice(0,8)}</p><p>{c('Participants','参与个体')} {e.match.request.fly_ids.map(f=>f.slice(0,8)).join(' / ')} · {e.match.request.bridge_profile||'legacy-v1'}</p><details><summary>{c('Evaluation version','评估版本')}</summary><code>{e.evaluation_context}</code></details>{e.match.status==='failed'&&<p>{c('Evaluation failed. No fitness is assigned.','评估执行失败，不记为 0 分。')} {e.match.error}</p>}{e.match.status==='verified'&&e.match.request.mode!=='sumo'&&e.scores?.some(s=>s===0)&&<p className="life-zero">{c('No food consumed during this evaluation window. This is not a claim of no activity or no ability.','在本次评估窗口内未摄食，不代表没有活动或没有能力。')}</p>}<div className="life-actions"><button className="text-link" disabled={e.match.status!=='verified'} onClick={()=>onReplay(e.match)}><Play size={13}/>{c('Behavior and neural replay','行为与神经回放')}</button><button className="text-link" disabled={busy||e.match.status!=='verified'} onClick={inspect}>{c('Inspect recorded observations','查看观测摘要')}</button></div>{error&&<p role="alert">{error}</p>}{data&&<div className="life-observation">{data.observations?data.observations.map(o=><div key={o.slot}><p>{c('Food consumed','摄食量')} {o.food_consumed.toFixed(4)} · {c('Sampled path','采样路径')} {o.sampled_path_mm.toFixed(2)} mm · {c('Final game energy','末态游戏能量')} {o.final_energy?.toFixed(2)??'—'}</p><p>{c('First intake record','首次摄食记录')} {o.first_intake_record_seconds===null?'—':o.first_intake_record_seconds.toFixed(3)+' s'} · {c('Exit time','出界时间')} {o.exit_seconds===null?'—':o.exit_seconds.toFixed(3)+' s'} · {c('Neural spikes','神经脉冲')} {o.total_spikes===null&&o.model_profile==='malecns-rate-cpu-v1'?c('Not applicable to continuous rates','连续模型不产生脉冲'):o.total_spikes?.toLocaleString()??'—'}</p><div className="individual-genes">{Object.entries(o.final_neural_activity||{}).map(([k,v])=><span key={k}>{k} {v.toFixed(2)} Hz</span>)}</div></div>):<p>{c('Recorded evidence is currently unavailable; no observation has been invented.','记录文件目前不可用，不生成推测观测值。')}</p>}<small>{c('Intake time is the event batch timestamp. Path is sampled thorax motion; mouth-to-food distance was not recorded. Neural values are final recorded population rates.','摄食时间为事件批次时间戳；路径来自胸部位置采样，未记录口器到食物的距离。神经数值为末帧记录的群体活动率。')}</small></div>}</article>
}
